### ISSUE TITLE
Associativity in syntax patterns

### ISSUE THREAD

**Issue by usaoc** [mflatt/shplait#5]
Currently, syntax patterns seem to always match left-associatively, even if `...` is used:

```
#lang shplait
fun parse1(s):
  match s
  | '$left + $right': values('$left', '$right')

fun parse2(s):
  match s
  | '$left + $right ...': values('$left', '$right ...')

fun parse3(s):
  match s
  | '$left ... + $right': values('$left ...', '$right')

def s = '1 + 2 + 3'

> parse1(s)
- Syntax * Syntax
values('1 + 2', '3')
> parse2(s)
- Syntax * Syntax
values('1 + 2', '3')
> parse3(s)
- Syntax * Syntax
values('1 + 2', '3')
```

Should the behavior be changed to match Rhombus so that 1. `parse1` matches right-associatively and 2. `...` matches greedily?  If not, the documentation should at least make this behavior clear.

**Comment by mflatt** [comment]
The documentation does need improvement. The rule for Shplait is that an escape matches any number of terms, and everything is greedy (i.e., either escapes that match a sequences or `...` repetitions).

Shplait's pattern language is meant to be convenient for a particular parsing strategy, where you can parse something like `1 * 2 + 3 * 4` by first trying `$left + $right` (recurring on a match) then trying `$left * $right`. Something more Rhombus-like would need `$left ... + $right ...` and then `$left ... * $right ...`.

Well, a pattern `$left ... + $right` would work in Rhombus, because and end-of-group `$right` implicitly matches a sequence. The special rule for an end-of-group escapes seems to makes things more convenient for macros, and enough to be worth the complexity in Rhombus, but it seems too complex for Shplait.

Rhombus's rules produce something that looks right-associative, but it's really about the way that different escapes are categorized. Meanwhile, the way greediness tends to make things left-associative is convenient for parsing with Shplait patterns.

**Comment by usaoc** [comment]
Thanks for the clarification.  I was a bit confused about the different rules, but I agree with the design.  The documentation also looks clearer now, so I’ll close the issue for now.
